"""add annotation_reviews table

Revision ID: 18d19aa85c3c
Revises: c1b7fbb8045a
Create Date: 2026-08-04 07:28:30.814409

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d19aa85c3c'
down_revision: Union[str, None] = 'c1b7fbb8045a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation_reviews',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dataset_view', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['annotators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_reviews_created_at'), 'annotation_reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_annotation_reviews_dataset_view'), 'annotation_reviews', ['dataset_view'], unique=False)
    op.create_index(op.f('ix_annotation_reviews_image_id'), 'annotation_reviews', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotation_reviews_image_id'), table_name='annotation_reviews')
    op.drop_index(op.f('ix_annotation_reviews_dataset_view'), table_name='annotation_reviews')
    op.drop_index(op.f('ix_annotation_reviews_created_at'), table_name='annotation_reviews')
    op.drop_table('annotation_reviews')
    # ### end Alembic commands ###
