"""phase 1a schema: annotators, annotation_state, annotation_history, dataset_classes

Revision ID: 3dd523697175
Revises: 
Create Date: 2026-08-04 05:35:39.588270

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3dd523697175'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dataset_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_view', sa.String(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_view', 'class_id', name='uq_dataset_classes_view_class')
    )
    op.create_index(op.f('ix_dataset_classes_dataset_view'), 'dataset_classes', ['dataset_view'], unique=False)
    op.create_table('annotation_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dataset_view', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('annotator_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_history_created_at'), 'annotation_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_annotation_history_dataset_view'), 'annotation_history', ['dataset_view'], unique=False)
    op.create_index(op.f('ix_annotation_history_image_id'), 'annotation_history', ['image_id'], unique=False)
    op.create_table('annotation_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_view', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['annotators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_view', 'image_id', name='uq_annotation_state_view_image')
    )
    op.create_index(op.f('ix_annotation_state_completed'), 'annotation_state', ['completed'], unique=False)
    op.create_index(op.f('ix_annotation_state_dataset_view'), 'annotation_state', ['dataset_view'], unique=False)
    op.create_index(op.f('ix_annotation_state_image_id'), 'annotation_state', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annotation_state_image_id'), table_name='annotation_state')
    op.drop_index(op.f('ix_annotation_state_dataset_view'), table_name='annotation_state')
    op.drop_index(op.f('ix_annotation_state_completed'), table_name='annotation_state')
    op.drop_table('annotation_state')
    op.drop_index(op.f('ix_annotation_history_image_id'), table_name='annotation_history')
    op.drop_index(op.f('ix_annotation_history_dataset_view'), table_name='annotation_history')
    op.drop_index(op.f('ix_annotation_history_created_at'), table_name='annotation_history')
    op.drop_table('annotation_history')
    op.drop_index(op.f('ix_dataset_classes_dataset_view'), table_name='dataset_classes')
    op.drop_table('dataset_classes')
    op.drop_table('annotators')
    # ### end Alembic commands ###
