"""add export gate exemptions, snapshot currently completed images

Revision ID: 9537304fbc09
Revises: 18d19aa85c3c
Create Date: 2026-08-04 08:57:55.034685

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9537304fbc09'
down_revision: Union[str, None] = '18d19aa85c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_gate_exemptions',
    sa.Column('dataset_view', sa.String(), nullable=False),
    sa.Column('image_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('dataset_view', 'image_id')
    )
    # ### end Alembic commands ###

    # Product-owner decision (see annotation_module_build_plan.md Phase 4):
    # grandfather everything already completed at the moment this migration
    # runs, so the new second-reviewer export gate only applies to images
    # that become completed from here on. One-time snapshot, not a live
    # view - see ExportGateExemption's docstring.
    op.execute(
        """
        INSERT INTO export_gate_exemptions (dataset_view, image_id)
        SELECT dataset_view, image_id FROM annotation_state WHERE completed = true
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('export_gate_exemptions')
    # ### end Alembic commands ###
