"""add annotator role column

Revision ID: c1b7fbb8045a
Revises: 3dd523697175
Create Date: 2026-08-04 07:20:24.834701

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b7fbb8045a'
down_revision: Union[str, None] = '3dd523697175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotators', sa.Column('role', sa.String(), server_default='annotator', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotators', 'role')
    # ### end Alembic commands ###
